### ISSUE TITLE
Error: Failed to upload file batch. ⚠️  Error: error sending request for url - operation timed out

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1111]
### 🐛 Bug Report

When running `wrangler publish` I get below error. My site is around 1 gigabyte, but each file is maximum 310 kb.

```
[simplenotezy:~/Projects/my-site]$ wrangler publish                                 (master✱)
🌀  Using namespace for Workers Site "__my-site-workers_sites_assets"
🌀  Uploading site files
Error: Failed to upload file batch. ⚠️  Error: error sending request for url (https://api.cloudflare.com/client/v4/accounts/XXXX/storage/kv/namespaces/XXXX/bulk): operation timed out
```

I got no clue why.

#### Environment

* operating system:
* output of `rustc -V`: command not found
* output of `node -v`: v10.16.3
* output of `wrangler -V`: 👷 ✨  wrangler 1.8.0

**Comment by simplenotezy** [comment]
I had a look at my speedtest, and for some strange reason it was at 20mb up/down - despite having 500/500. So I restarted my pc, did a new speedtest, now showing 300 down, 200 up, and the publish completed in less than 5 minutes - don't know what happened there.

**Comment by gabbifish** [comment]
Hi @simplenotezy! Sorry this is causing you trouble. So, it looks like your publish ultimately worked! We've definitely received some feedback that Wrangler sometimes times out during large uploads if users don't have a generous upload bandwidth; I'm going to tag this issue in the overarching issue about upload bandwidth troubles, and we'll continue investigating there.

**Comment by EverlastingBugstopper** [comment]
this should be fixed with 1.10.1

**Comment by simplenotezy** [comment]
Good job!

**Comment by vyktorjonas** [comment]
any way to fix this? I just ran into this issue so I don't think it's fixed, my internet is 10mb
