### ISSUE TITLE
Unable to set secrets on a new environment, which causes publish to fail

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#1129]
#### Environment

* operating system: mac os x 10.13.6
* output of `rustc -V`: n/a (not installed)
* output of `node -v`: v12.1.0
* output of `wrangler -V`: wrangler 1.8.1

#### Steps to reproduce

The `wrangler.toml` for the project can be found here: https://github.com/signalnerve/workers-auth0-example/commit/cdc45d2635fc71978aeb308fcb322a3e7d829ec7 (link to commit adding `wrangler.toml` environment)

#### What did you expect to see?

I'm able to set secrets and publish a new environment as defined in my `wrangler.toml`.

#### What did you see instead?

After defining a new environment in my [`wrangler.toml`](https://github.com/signalnerve/workers-auth0-example/commit/cdc45d2635fc71978aeb308fcb322a3e7d829ec7), I'm unable to create a new secret using `wrangler secret put`:

```bash
iMac:my-auth-test kristian$ wrangler secret put AUTH0_DOMAIN -e zone
Enter the secret text you'd like assigned to the variable AUTH0_DOMAIN on the script named my-auth-test-zone:
test
🌀  Creating the secret for script name my-auth-test-zone
🌀  Worker my-auth-test-zone doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: AUTH0_DOMAIN is not defined\n  at line 7\n  at line 1 in n\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}
```

The accompanying code that is failing is this config object in my code:

```js
const auth0 = {
  domain: AUTH0_DOMAIN,
  clientId: AUTH0_CLIENT_ID,
  clientSecret: AUTH0_CLIENT_SECRET,
  callbackUrl: AUTH0_CALLBACK_URL,
}
```

Because of this, I'm also unable to run `wrangler publish`:

```bash
iMac:my-auth-test kristian$ wrangler publish -e zone
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 3 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: AUTH0_DOMAIN is not defined\n  at line 7\n  at line 1 in n\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}
```

**Comment by EverlastingBugstopper** [comment]
this is fixed now with draft worker uploads

**Comment by signalnerve** [comment]
hey @EverlastingBugstopper, did this make it into the 1.9.0 rc? i'm still seeing this error on that version:

```
auth-runthrough$ wrangler secret put AUTH0_DOMAIN
Enter the secret text you'd like assigned to the variable AUTH0_DOMAIN on the script named auth-runthrough:
dev-tft4si-b.auth0.com
🌀  Creating the secret for script name auth-runthrough
🌀  Worker auth-runthrough doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: AUTH0_DOMAIN is not defined\n  at line 7\n  at line 1 in t\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}

auth-runthrough$ wrangler --version
👷 ✨  wrangler 1.9.0-rc.0
```

**Comment by EverlastingBugstopper** [comment]
hmmm... i'm not sure if it made it to the rc, wasn't around when it's cut. It does work on master though

```
$ wrangler secret put INPUT
Enter the secret text you'd like assigned to the variable INPUT on the script named secret-test:
world!
🌀  Creating the secret for script name secret-test
🌀  Worker secret-test doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
✨  Success! Uploaded secret INPUT.
```

**Comment by signalnerve** [comment]
good to know! i can patch around it for now by doing `let AUTH0_DOMAIN`, i think by the time this tutorial i'm writing comes out, i won't have to patch it :)

**Comment by ObsidianMinor** [comment]
I'm still encountering this on master using the site template.
```
🚀️ ➟ wrangler secret put AUTH0_DOMAIN
Enter the secret text you'd like assigned to the variable AUTH0_DOMAIN on the script named my-auth-example:
inlining.auth0.com
 Creating the secret for script name my-auth-example
 Worker my-auth-example doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: AUTH0_DOMAIN is not defined\n  at line 7\n  at line 1 in t\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}
```

**Comment by EverlastingBugstopper** [comment]
@ObsidianMinor - are you on the latest version of Wrangler? (`wrangler --version` should be 1.9.0)

**Comment by ObsidianMinor** [comment]
Yep Wrangler 1.9 through npm

**Comment by adervish** [comment]
I'm on wrangler 1.10.3 and experiencing this issue

**Comment by rslonik** [comment]
`wrangler 1.11.0` here with the same issue.

**Comment by jcapogna** [comment]
I'm also having this issue on 1.11.0. I was able to create a secret in the default environment, but not other environments.

**Comment by dilsonnn** [comment]
Had the same issue, turns out I renamed the project on cloudflare and then tried to publish with the old name, which was creating a new worker on a new worker domain.

Renaming the name in wrangler.toml solved the issue.

**Comment by XavM** [comment]
Same issue using wrangler 1.13.0
(Work around by first creating a worker with the same name thrue dash UI)

**Comment by jcapogna** [comment]
I just ran into this problem again adding new secrets to an existing worker. After bashing my head for a while, I realized that you must add add secrets via the Wrangler CLI. Adding secrets via the web UI results in this problem

Hope that helps someone. Also created #1958 to document

**Comment by signalnerve** [comment]
@cloudflare/wrangler considering all the bug reports here, would it be appropriate to re-open this issue? it seems like this may still be a problem w/ wrangler

**Comment by jcapogna** [comment]
I just created a new worker for the first time in a while and hit this problem. I don't think the draft worker solution is working - the creation of the draft worker failed for me due to the secret not being defined.

Repro steps:
- Deploy worker to new environment for the first time. Note that it fails to due a secret not being defined. 
- Run `wrangler secret put -e new_environment SECRET_NAME` to create new secret. Wrangler attempts to create a draft worker but fails due to the secret not being defined. 

```
$ wrangler secret put -e staging ABLY_KEY
Enter the secret text you'd like assigned to the variable ABLY_KEY on the script named worker-staging:
SECRET
🌀  Creating the secret for script name worker-staging
🌀  Worker worker-staging doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: ABLY_KEY is not defined\n  at line 22\n  at line 1 in r\n  at line 22\n  at line 1 in r\n  at line 22\n  at line 1 in r\n  at line 22\n  at line 1 in r\n  at line 1\n  at line 1\n"
    }
  ],
  "messages": []
}
```

**Comment by jcapogna** [comment]
The workaround of creating a worker with the same name in the web UI does work. Just create it with the hello world example code already defined in the web UI, run `wrangler secret put` to define your secrets, and then run `wrangler publish`.

**Comment by MartinRoesch2** [comment]
So what do I do in the meantime? 
Use the workaround described by jcapogna on Jun 17?

**Comment by whereisaaron** [comment]
This chicken and egg problem bits every time you add a secret to your code then try to set its value with `wrangler secret put`. It still happens in 1.19.0. On another is someone suggested always referring to secrets as `globalThis.SECRET` so that it can be undefined during the publish. This seems like a rough edge on the secrets system that's a common part of the new user experience.

**Comment by tinjaw** [comment]
Still having this issue on August 29

**Comment by mastrgates** [comment]
We also just hit this issue today as well. Trying to build and deploy a wrangler project that references secrets and uses the wrangler-action to inject the secrets during the github action fail with the same error 
```
[0] Error: Something went wrong with the request to Cloudflare...
[0] Uncaught ReferenceError: SECRET_NAME is not defined
```

**Comment by RicardoViteriR** [comment]
I just faced the same issue: 

I had to use @signalnerve solution using let

Example code:
```ts
let EMAIL_ACCESS_KEY;
let EMAIL_SECRET_ACCESS_KEY;
const accessKeyId: string = EMAIL_ACCESS_KEY;
const secretAccessKey: string = EMAIL_SECRET_ACCESS_KEY;
```

**Comment by lookfirst** [comment]
The globalThis "workaround" isn't working for me at all.

**Comment by alexandernst** [comment]
We were also hit by this. Is there anything we can do to speed up this? Maybe the bug isn't fixed yet because there are no clear repro steps?

**Comment by lookfirst** [comment]
@alexandernst This is the workaround...

https://github.com/cloudflare/wrangler/issues/1418#issuecomment-732761146

**Comment by MauriceArikoglu** [comment]
For anyone struggling with this issue and looking for a workaround with typescript and the "wrangler chicken egg problem" regarding secrets - this worked for me in typescript:
- A d.ts file in a typings dir, included via tsconfig (in include paths) with the following content

```
declare global {

  type GS = typeof globalThis & GlobalSecrets
  
  interface GlobalSecrets {
    TYPED_SECRET1: string;
    TYPED_SECRET2: string;
  }
}

export {}
```

Usage within the handlers:
`(globalThis as GS).TYPED_SECRET1`

Hope this helps anyone...

**Comment by RFebrians** [comment]
I'm on wrangler 1.19.8 and experiencing the same issues , 

But somehow i was able to resolve it , by commenting all the SESSION_SECRET from the codes and .env ,

then after success added secret key , i'm restore the SESSION_SECRET to code and push then everything worked fine

**Comment by petebacondarwin** [comment]
I just tried this on Wrangler 2.0.14 and cannot reproduce the problem, so I believe it is fixed.
Please try updating to the latest version of Wrangler:

```sh
npm -g uninstall @cloudflare/wrangler
npm -g install wrangler@latest
```

**Comment by lookfirst** [comment]
Confirmed fixed. Thank you @petebacondarwin
