### ISSUE TITLE
status code 500: npm install wrangler

### ISSUE THREAD

**Issue by pew** [cloudflare/wrangler#1874]
#### Describe the bug

I'm not able to install the latest wrangler version via npm for a couple of hours now, I did work earlier today, last week etc. on my Apple Silicon Mac.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. `npm install -g @cloudflare/wrangler`

```
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! Downloading release from https://workers.cloudflare.com/get-npm-wrangler-binary/1.16.0/aarch64-apple-darwin
npm ERR! Error fetching release: Request failed with status code 500
```

opening the URL in a Browser also shows the error 500:

```
Error 1101 Ray ID: 645887795ec506a6 • 2021-04-25 15:15:51 UTC
Worker threw exception
```

#### Expected behavior

Install wrangler as before.

#### Environment and versions

Fill out the following information about your environment.

* operating system: macOS 11.2.3 (apple silicon)
* output of `node -v`: v14.16.1
* npm version: 7.11.1

**Comment by leeanson19** [comment]
The Cloudflare team said this package does not support M1 Mac yet. Try using Cargo to install Wrangler for your M1 Mac. By the way, you might face some troubles while you use "wrangler generate my-worker" command. You can find the solution in #1685

**Comment by xtuc** [comment]
I'm closing this issue it's a duplicate of  https://github.com/cloudflare/wrangler/issues/1685.

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

**Comment by pew** [comment]
it works with `@cloudflare/wrangler` and with `@cloudflare/wrangler@1.16.1` but still not with `@beta` to use Durable Objects. This worked a couple of days ago.
